-- COMANDO PARA CRIAR A COLUNA PAÍS
ALTER TABLE Municipios_Brasileiros ADD COLUMN País;

-- COMANDO PARA ALTERAR A COLUNA E ADD O VALOR "BRASIL"
UPDATE Municipios_Brasileiros SET País="Brasil";

-- COMANDO PARA DELETAR A COLUNA PAÍS
ALTER TABLE Municipios_Brasileiros DROP COLUMN País;